Layout/IndentationWidth:
  Width: 4

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 180

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength: 
  Max: 40

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact
